%workSpace
clear all
clc
close all
positionList = [];
eulerAngleList = [];
theta_min = -2*pi;
theta_max = 2*pi;
for k = 1:1e4
    q = theta_max - (theta_max-theta_min)*rand(1,6);
    poseRef = ur5FK(q);
    positionList = [positionList;poseRef(1:3)];
    eulerAngleList = [eulerAngleList;poseRef(4:end)];
end
 
[x,y,z]=deal(positionList(:,1),positionList(:,2),positionList(:,3));
[alpha,beta,gamma]=deal(eulerAngleList(:,1),eulerAngleList(:,2),eulerAngleList(:,3));

figure
subplot(1,2,1)
scatter3(x,y,z,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[0 .75 .75],...
        'Marker', 'o',...
         'SizeData', 25);
 xlabel('x/m')
 ylabel('y/m')
 zlabel('z/m')
view(-30,10)

% subplot(1,2,2)
figure
scatter3(alpha,beta,gamma,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor',[0 .75 .75],...
        'Marker', 'o',...
         'SizeData', 15);
 xlabel('\alpha/rad')
 ylabel('\beta/rad')
 zlabel('\gamma/rad')
view(-60,10)

%%

figure
% subplot(1,2,1)
scatter3(x,y,0*z,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','r',...
        'Marker', 'o',...
         'SizeData', 25);
         hold on
scatter3(0*x,y,z,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','g',...
        'Marker', 'o',...
         'SizeData', 25);
scatter3(x,0*y,z,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','b',...
        'Marker', 'o',...
         'SizeData', 25);     
 hold off                     
xlabel('x/m')
ylabel('y/m')
zlabel('z/m')
view(-30,10)


% subplot(1,2,2)
figure
scatter3(alpha,beta,0*gamma,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','r',...
        'Marker', 'o',...
         'SizeData', 25);
         hold on
scatter3(0*alpha,beta,gamma,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','g',...
        'Marker', 'o',...
         'SizeData', 25);
scatter3(alpha,0*beta,gamma,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','b',...
        'Marker', 'o',...
         'SizeData', 25);     
 hold off                     
xlabel('\alpha/rad')
ylabel('\beta/rad')
zlabel('\gamma/rad')
view([5,5,10])

